Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    
    config.vm.provider "virtualbox" do |v|
      v.name = "django-segmented-uploads"
    end
    
    config.vm.network "forwarded_port", guest: 8040, host: 8040
    config.vm.provision :shell, path: "provision.sh"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../", "/vagrant"
end
