# Generated by Django 3.0.3 on 2020-02-26 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import segmented_uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('session', models.CharField(db_index=True, default=None, editable=False, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, editable=False, upload_to=segmented_uploads.models.instance_upload_to)),
                ('digest', models.CharField(blank=True, editable=False, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('token', 'user'), ('token', 'session')},
            },
            bases=(segmented_uploads.models.UploadToMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UploadSecret',
            fields=[
                ('value', models.CharField(default=segmented_uploads.models.generate_secret_value, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secrets', to='segmented_uploads.Upload')),
            ],
        ),
        migrations.CreateModel(
            name='UploadSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=segmented_uploads.models.instance_upload_to)),
                ('index', models.IntegerField(db_index=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='segmented_uploads.Upload')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('index', 'upload')},
            },
            bases=(segmented_uploads.models.UploadToMixin, models.Model),
        ),
    ]
