# Generated by Django 3.0.7 on 2020-06-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmented_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='lingering',
            field=models.BooleanField(default=False),
        ),
    ]
